### PR TITLE
Update runtime

### LINKED ISSUE #3: runtime to be updated
flatpak says runtime has reached end of life cycle

Info: org.freedesktop.Platform//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Applications using this runtime:
   net.blockout.BlockOutII

### PR DESCRIPTION
**Pull request by bbhtt**
- Updates the submodule.

- Updates the runtime to 21.08.

- Drops all SDL, SDL mixer and smpeg sources and patches, these are included in the submodule.

- Adds width and height properties to screenshot tag in appdata, these seem to be required now to display the image.

- Adds a gitignore

Hopefully will fix https://github.com/flathub/net.blockout.BlockOutII/issues/3

Some of the dependencies are from 2003... I'll try.

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build net.blockout.BlockOutII

**Comment by bbhtt** [comment]
bot, build net.blockout.BlockOutII

**Comment by bbhtt** [comment]
Managed to build it locally on my machine, so let's try again...

**Comment by bbhtt** [comment]
Hi, @cosimoc , are you still around? Please review this PR. 

cc @nedrichards also, since you committed last and seem to have access.

Also, hi @dassuan did you/do you still use this? It'd be very helpful if you can test [91837](https://flathub.org/builds/#/builders/32/builds/91837) and see if everything works.

**Comment by bbhtt** [comment]
The screenshots are gone.

Edit. Should be fixed.

**Comment by dassuan** [comment]
> Also, hi @dassuan did you/do you still use this? It'd be very helpful if you can test [91837](https://flathub.org/builds/#/builders/32/builds/91837) and see if everything works.


hi @bbhtt,

Tested build 91837 and it all works, seems to run a bit smoother now. Still eats astonishing amounts of CPU action for a little program that ran on MSDos on a 286 in the eighties. Thanks for the efforts.

dassuan

**Comment by bbhtt** [comment]
@hfiguiere Thank you!

**Pull request merged**
